---
# - name: "2.1.1 | PATCH | Ensure xinetd is not installed"
#   apt:
#       name: xinetd
#       state: absent
#   when:
#       - ubtu20cis_rule_2_1_1
#   tags:
#       - level1-server
#       - level1-workstation
#       - patch
#       - rule_2.1.1
#       - xinetd

# - name: "2.1.2 | PATCH | Ensure openbsd-inetd is not installed"
#   apt:
#       name: openbsd-inetd
#       state: absent
#   when:
#       - ubtu20cis_rule_2_1_2
#   tags:
#       - level1-server
#       - level1-workstation
#       - patch
#       - rule_2.1.2
#       - openbsd-inetd

- name: "2.1.1.1 | PATCH | Ensure time synchronization is in use"
  apt:
      name: "{{ ubtu20cis_time_sync_tool }}"
      state: present
  when:
      - ubtu20cis_rule_2_1_1_1
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.1.1
      - chrony

- name: "2.1.1.2 | PATCH | Ensure systemd-timesyncd is configured"
  block:
      - name: "2.1.1.2 | PATCH | Ensure systemd-timesyncd is configured | Remove ntp and chrony"
        apt:
            name: ['ntp', 'chrony']
            state: absent

      - name: "2.1.1.2 | PATCH | Ensure systemd-timesyncd is configured | Set configuration for systemd-timesyncd"
        lineinfile:
            path: /etc/systemd/timesyncd.conf
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
            insertafter: "{{ item.insertafter }}"
        with_items:
            - { regexp: '^\[Time\]', line: '[Time]', insertafter: EOF }
            - { regexp: '^#NTP|^NTP', line: 'NTP={{ ubtu20cis_ntp_server_list }}', insertafter: '\[Time\]' }
            - { regexp: '^#FallbackNTP|^FallbackNTP', line: 'FallbackNTP={{ ubtu20cis_ntp_fallback_server_list }}', insertafter: '\[Time\]' }
            - { regexp: '^#RootDistanceMaxSec|^RootDistanceMaxSec', line: 'RootDistanceMaxSec=1', insertafter: '\[Time\]'}

      - name: "2.1.1.2 | PATCH | Ensure systemd-timesyncd is configured | Start and enable the systemd-timesyncd service"
        systemd:
            name: systemd-timesyncd.service
            state: started
            enabled: yes
            masked: no

      - name: "2.1.1.2 | PATCH | Ensure systemd-timesyncd is configured | Set timedatectl to ntp"
        command: timedatectl set-ntp true
  when:
      - ubtu20cis_rule_2_1_1_2
      - ubtu20cis_time_sync_tool == "systemd-timesyncd"
  tags:
      - level1-server
      - level1-workstation
      - manual
      - patch
      - rule_2.1.1.2
      - systemd-timesyncd

- name: "2.1.1.3 | PATCH | Ensure chrony is configured"
  block:
      - name: "2.1.1.3 | PATCH | Ensure chrony is configured | Remove ntp"
        apt:
            name: ntp
            state: absent

      - name: "2.1.1.3 | PATCH | Ensure chrony is configured | Disable/Mask systemd-timesyncd"
        systemd:
            name: systemd-timesyncd
            state: stopped
            enabled: no
            masked: yes

      - name: "2.1.1.3 | AUDIT | Ensure chrony is configured | Check for chrony user"
        shell: grep {{ ubtu20cis_chrony_user }} /etc/passwd
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu20cis_2_1_1_3_chrony_user_status

      - name: "2.1.1.3 | PATCH | Ensure chrony is configured | Set chrony.conf file"
        template:
            src: chrony.conf.j2
            dest: /etc/chrony/chrony.conf
            owner: root
            group: root
            mode: 0644

      - name: "2.1.1.3 | PATCH | Ensure chrony is configured | Create chrony user"
        user:
            name: "{{ ubtu20cis_chrony_user }}"
            shell: /usr/sbin/nologin
            system: true
        when: ubtu20cis_2_1_1_3_chrony_user_status.stdout != ""

      - name: "2.2.1.3 | PATCH | Ensure chrony is configured | Set option to use chrony user"
        lineinfile:
            path: /etc/default/chrony
            regexp: '^DAEMON_OPTS'
            line: 'DAEMON_OPTS="-u _chrony"'
  when:
      - ubtu20cis_rule_2_1_1_3
      - ubtu20cis_time_sync_tool == "chrony"
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.1.3
      - chrony

- name: "2.1.1.4 | PATCH | Ensure ntp is configured"
  block:
      - name: "2.1.1.4 | PATCH | Ensure ntp is configured | Remove chrony"
        apt:
            name: chrony
            state: absent

      - name: "2.1.1.4 | PATCH | Ensure ntp is configured | Disable/Mask systemd-timesyncd"
        systemd:
            name: systemd-timesyncd
            state: stopped
            enabled: no
            masked: yes

      - name: "2.1.1.4 | PATCH | Ensure ntp is configured | Set ntp.conf settings"
        template:
            src: ntp.conf.j2
            dest: /etc/ntp.conf
            owner: root
            group: root
            mode: 0644

      - name: "2.1.1.4 | PATCH | Ensure ntp is configured | Modify sysconfig/ntpd"
        lineinfile:
            path: /etc/sysconfig/ntpd
            regexp: "{{ item.regexp }}"
            line: "{{ item. line }}"
            create: yes
        with_items:
            - { regexp: '^OPTIONS', line: 'OPTIONS="-u ntp:ntp"'}
            - { regexp: '^NTPD_OPTIONS', line: 'NTPD_OPTIONS="-u ntp:ntp"' }

      - name: "2.1.1.4 | PATCH | Ensure ntp is configured | Modify /etc/init.d/npt"
        lineinfile:
            path: /etc/init.d/ntp
            regexp: '^RUNAUSER'
            line: 'RUNAUSER=npt'
  when:
      - ubtu20cis_rule_2_1_1_4
      - ubtu20cis_time_sync_tool == "ntp"
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.1.4
      - ntp

- name: "2.1.2 | PATCH | Ensure X Window System is not installed"
  apt:
      name: xserver-xorg*
      state: absent
  when:
      - ubtu20cis_rule_2_1_2
      - not ubtu20cis_desktop_required
  tags:
      - level1-server
      - patch
      - rule_2.1.2
      - xwindows

- name: "2.1.3 | PATCH | Ensure Avahi Server is not installed"
  block:
      - name: "2.1.3 | PATCH | Ensure Avahi Server is not installed | Stop/Disable avahi-daemon.service"
        service:
            name: avahi-daemon.service
            state: stopped
            enabled: no
        when: avahi_service_status.stdout == "loaded"

      - name: "2.1.3 | PATCH | Ensure Avahi Server is not installed | Stop/Disable avahi-daemon.socket"
        service:
            name: avahi-daemon.socket
            state: stopped
            enabled: no
        when: avahi_service_status.stdout == "loaded"

      - name: "2.1.3 | PATCH | Ensure Avahi Server is not installed | Remove avahi-daemon"
        apt:
            name: avahi-daemon
            state: absent
  when:
      - ubtu20cis_rule_2_1_3
      - not ubtu20cis_avahi_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.3
      - avahi
      - services

- name: "2.1.4 | PATCH | Ensure CUPS is not installed"
  apt:
      name: cups
      state: absent
  when:
      - ubtu20cis_rule_2_1_4
      - not ubtu20cis_cups_server
  tags:
      - level1-server
      - level2-workstation
      - patch
      - rule_2.1.4
      - cups
      - services

- name: "2.1.5 | PATCH | Ensure DHCP Server is not installed"
  apt:
      name: isc-dhcp-server
      state: absent
  when:
      - ubtu20cis_rule_2_1_5
      - not ubtu20cis_dhcp_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.5
      - dhcp
      - services

- name: "2.1.6 | PATCH | Ensure LDAP server is not installed"
  apt:
      name: slapd
      state: absent
  when:
      - ubtu20cis_rule_2_1_6
      - not ubtu20cis_ldap_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.6
      - ldap
      - services

- name: "2.1.7 | PATCH | Ensure NFS is not installed"
  apt:
      name: rpcbind
      state: absent
  when:
      - ubtu20cis_rule_2_1_7
      - not ubtu20cis_nfs_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.7
      - nfs
      - rpc
      - services

- name: "2.1.8 | PATCH | Ensure DNS Server is not installed"
  apt:
      name: bind9
      state: absent
  when:
      - ubtu20cis_rule_2_1_8
      - not ubtu20cis_dns_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.8
      - dns
      - service

- name: "2.1.9 | PATCH | Ensure FTP Server is not installed"
  apt:
      name: vsftpd
      state: absent
  when:
      - ubtu20cis_rule_2_1_9
      - not ubtu20cis_vsftpd_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.9
      - ftp
      - service

- name: "2.1.10 | PATCH | Ensure HTTP server is not installed"
  apt:
       name: apache2
       state: absent
  when:
      - ubtu20cis_rule_2_1_10
      - not ubtu20cis_httpd_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.10
      - httpd
      - service

- name: "2.1.11 | PATCH | Ensure IMAP and POP3 server are not installed"
  apt:
      name: ['dovecot-imapd', 'dovecot-pop3d']
      state: absent
  when:
      - ubtu20cis_rule_2_1_11
      - not ubtu20cis_dovecot_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.11
      - dovecot
      - service

- name: "2.1.12 | PATCH | Ensure Samba is not installed"
  apt:
      name: samba
      state: absent
  when:
      - ubtu20cis_rule_2_1_12
      - not ubtu20cis_smb_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.12
      - samba
      - service

- name: "2.1.13 | PATCH | Ensure HTTP Proxy Server is not installed"
  apt:
      name: squid
      state: absent
  when:
      - ubtu20cis_rule_2_1_13
      - not ubtu20cis_squid_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.13
      - http_proxy
      - service

- name: "2.1.14 | PATCH | Ensure SNMP Server is not installed"
  apt:
      name: snmpd
      state: absent
  when:
      - ubtu20cis_rule_2_1_14
      - not ubtu20cis_snmp_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.14
      - snmp
      - service

- name: "2.1.15 | PATCH | Ensure mail transfer agent is configured for local-only mode"
  block:
      - name: "2.1.15 | PATCH | Ensure mail transfer agent is configured for local-only mode | Make changes if exim4 installed"
        lineinfile:
            path: /etc/exim4/update-exim4.conf.conf
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
        with_items:
            - { regexp: '^dc_eximconfig_configtype', line: "dc_eximconfig_configtype='local'" }
            - { regexp: '^dc_local_interfaces', line: "dc_local_interfaces='127.0.0.1 ; ::1'" }
            - { regexp: '^dc_readhost', line: "dc_readhost=''" }
            - { regexp: '^dc_relay_domains', line: "dc_relay_domains=''" }
            - { regexp: '^dc_minimaldns', line: "dc_minimaldns='false'" }
            - { regexp: '^dc_relay_nets', line: "dc_relay_nets=''" }
            - { regexp: '^dc_smarthost', line: "dc_smarthost=''" }
            - { regexp: '^dc_use_split_config', line: "dc_use_split_config='false'" }
            - { regexp: '^dc_hide_mailname', line: "dc_hide_mailname=''" }
            - { regexp: '^dc_mailname_in_oh', line: "dc_mailname_in_oh='true'" }
            - { regexp: '^dc_localdelivery', line: "dc_localdelivery='mail_spool'" }
        notify: restart exim4
        when: ubtu20_cis_mail_transfer_agent == "exim4"

      - name: "2.1.15 | PATCH | Ensure mail transfer agent is configured for local-only mode | Make changes if postfix is installed"
        lineinfile:
            path: /etc/postfix/main.cf
            regexp: '^(#)?inet_interfaces'
            line: 'inet_interfaces = loopback-only'
        notify: restart postfix
        when: ubtu20_cis_mail_transfer_agent == "postfix"

      - name: "2.1.15 | PATCH | Ensure mail transfer agent is configured for local-only mode | Message out other main agents"
        debug:
            msg:
                - "Warning!! You are not using either exim4 or postfix"
                - "Please review your vendors documentation to configure local-only mode"
        when: ubtu20_cis_mail_transfer_agent == "other"
  when:
      - ubtu20cis_rule_2_1_15
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_2.1.15
      - postfix

- name: "2.1.16 | PATCH | Ensure rsync service is not installed"
  apt:
      name: rsync
      state: absent
  when:
      - ubtu20cis_rule_2_1_16
      - not ubtu20cis_rsync_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.16
      - rsync

- name: "2.1.17 | PATCH | Ensure NIS Server is not installed"
  apt:
      name: nis
      state: absent
  when:
      - ubtu20cis_rule_2_1_17
      - not ubtu20cis_nis_server
  tags:
      - level1-server
      - level1-workstation
      - rule_2.1.17
      - nis
      - service

- name: "2.2.1 | PATCH | Ensure NIS Client is not installed"
  apt:
      name: nis
      state: absent
  when:
      - ubtu20cis_rule_2_2_1
      - not ubtu20cis_nis_required
  tags:
      - level1-server
      - level1-workstation
      - rule_2.2.1
      - nis

- name: "2.2.2 | PATCH | Ensure rsh client is not installed"
  apt:
      name: rsh-client
      state: absent
  when:
      - ubtu20cis_rule_2_2_2
      - not ubtu20cis_rsh_required
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.2
      - rsh

- name: "2.2.3 | PATCH | Ensure talk client is not installed"
  apt:
      name: talk
      state: absent
  when:
      - ubtu20cis_rule_2_2_3
      - not ubtu20cis_talk_required
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.3
      - talk

- name: "2.2.4 | PATCH | Ensure telnet client is not installed"
  apt:
      name: telnet
      state: absent
  when:
      - ubtu20cis_rule_2_2_4
      - not ubtu20cis_telnet_required
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.4
      - telnet

- name: "2.2.5 | PATCH | Ensure LDAP client is not installed"
  apt:
      name: ldap-utils
      state: absent
  when:
      - ubtu20cis_rule_2_2_5
      - not ubtu20cis_ldap_clients_required
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.5
      - ldap

- name: "2.2.6 | PATCH | Ensure RPC is not installed"
  apt:
      name: rpcbind
      state: absent
  when:
      - ubtu20cis_rule_2_2_6
      - not ubtu20cis_rpc_required
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.6
      - rpbc

- name: "2.3 | AUDIT | Ensure nonessential services are removed or masked"
  block:
      - name: "2.4 | AUDIT | Ensure nonessential services are removed or masked | Check for services"
        shell: lsof -i -P -n | grep -v "(ESTABLISHED)"
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu20cis_2_4_services

      - name: "2.4 | AUDIT | Ensure nonessential services are removed or masked | Message out running services"
        debug:
            msg:
                - "Warning!! Below are the running services. Please review and remove as well as mask un-needed services"
                - "{{ ubtu20cis_2_4_services.stdout_lines }}"
  when:
      - ubtu20cis_rule_2_4
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_2.4
      - services"
