---
- name: "SECTION | 2.1.1 | Configure Time Synchronization"
  ansible.builtin.import_tasks: cis_2.1.1.x.yml

- name: "SECTION | 2.1.2 | Configure chrony"
  ansible.builtin.import_tasks: cis_2.1.2.x.yml
  when: ubtu20cis_time_sync_tool == "chrony"

- name: "SECTION | 2.1.3 | Configure systemd-timesyncd"
  ansible.builtin.import_tasks: cis_2.1.3.x.yml
  when: ubtu20cis_time_sync_tool == "timesyncd"

- name: "SECTION | 2.1.4 | Configure NTP"
  ansible.builtin.import_tasks: cis_2.1.4.x.yml
  when: ubtu20cis_time_sync_tool == "ntp"

- name: "SECTION | 2.2 | Special Purpose Services"
  ansible.builtin.import_tasks: cis_2.2.x.yml

- name: "SECTION | 2.3 | Service Clients"
  ansible.builtin.import_tasks: cis_2.3.x.yml

- name: "SECTION | 2.4 | Ensure nonessential services are removed or masked"
  ansible.builtin.import_tasks: cis_2.4.yml
