---

- name: "1.4.1 | PATCH | Ensure bootloader password is set"
  block:
      - name: "1.4.1 | PATCH | Ensure bootloader password is set | set superusers and password"
        ansible.builtin.lineinfile:
            path: "{{ ubtu20cis_grub_user_file }}"
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
            state: present
            insertafter: "{{ item.after | default(omit) }}"
            create: true
        loop:
            - { regexp: '^set superusers', line: 'set superusers="{{ ubtu20cis_grub_user }}"' }
            - { regexp: '^password_pbkdf2 {{ ubtu20cis_grub_user }} grub.pbkdf2.*', line: 'password_pbkdf2 {{ ubtu20cis_grub_user }} {{ ubtu20cis_bootloader_password_hash }}', after: 'set superusers="' }
        notify: Grub update

      - name: "1.4.1 | PATCH | Ensure bootloader password is set | allow unrestricted boot"
        ansible.builtin.lineinfile:
            path: "/etc/grub.d/10_linux"
            regexp: '(^CLASS="--class gnu-linux --class gnu --class os).*"$'
            line: '\g<1> --unrestricted"'
            backrefs: true
        notify: Grub update
        when: not ubtu20cis_ask_passwd_to_boot
  when:
      - ubtu20cis_set_boot_pass
      - ubtu20cis_rule_1_4_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.4.1
      - grub

- name: "1.4.2 | PATCH | Ensure permissions on bootloader config are configured"
  block:
      - name: "1.4.2 | AUDIT | Ensure permissions on bootloader config are configured | Check for Grub file"
        ansible.builtin.stat:
            path: "{{ ubtu20cis_grub_file }}"
        check_mode: false
        register: ubtu20cis_1_4_2_grub_cfg_status

      - name: "1.4.2 | PATCH | Ensure permissions on bootloader config are configured | Set permissions"
        ansible.builtin.file:
            path: "{{ ubtu20cis_grub_file }}"
            owner: root
            group: root
            mode: 0600
        when:
            - ubtu20cis_1_4_2_grub_cfg_status.stat.exists
  when:
      - ubtu20cis_rule_1_4_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.4.2
      - grub

- name: "1.4.3 | PATCH | Ensure authentication required for single user mode"
  ansible.builtin.user:
      name: "{{ ubtu20cis_grub_user }}"
      password: "{{ ubtu20cis_bootloader_password_hash }}"
  when:
      - ubtu20cis_rule_1_4_3
      - ubtu20cis_set_boot_pass
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.4.3
      - passwd
