---
- name: "1.4.1 | PATCH | Ensure permissions on bootloader config are not overridden"
  block:
      - name: "1.4.1 | PATCH | Ensure permissions on bootloader config are not overridden | Change chmod setting"
        ansible.builtin.replace:
            path: /usr/sbin/grub-mkconfig
            regexp: 'chmod\s\d\d\d\s\${grub_cfg}.new'
            replace: 'chmod 400 ${grub_cfg}.new'

      - name: "1.4.1 | PATCH | Ensure permissions on bootloader config are not overridden | Remove check on password"
        ansible.builtin.lineinfile:
            path: /usr/sbin/grub-mkconfig
            regexp: 'if \[ \"x\$\{grub_cfg\}\" != "x" \] && ! grep "\^password" \${grub_cfg}.new'
            line: if [ "x${grub_cfg}" != "x" ]; then
  when:
      - ubtu20cis_rule_1_4_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.4.1
      - grub

# Variables listed in 1.4.2 will need to be set for your environment

- name: "1.4.2 | PATCH | Ensure bootloader password is set"
  block:
      - name: "1.4.2 | PATCH | Ensure bootloader password is set | set boot password"
        ansible.builtin.lineinfile:
            path: "{{ ubtu20cis_grub_user_file}}"
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
            insertafter: "{{ item.after | default(omit) }}"
        no_log: true
        loop:
            - { regexp: '^set superusers=', line: 'set superusers="{{ ubtu20cis_grub_users }}"' }
            - { regexp: '^password_pbkdf2', line: 'password_pbkdf2 {{ ubtu20cis_grub_users }} {{ ubtu20cis_grub_pw }}', after: '^set superusers=' }

      - name: "1.4.2 | PATCH | Ensure bootloader password is set | allow unrestricted boot"
        ansible.builtin.lineinfile:
            path: "/etc/grub.d/10_linux"
            regexp: '(^CLASS="--class gnu-linux --class gnu --class os).*"$'
            line: '\g<1> --unrestricted"'
            backrefs: true
        when: not ubtu20cis_ask_passwd_to_boot
  notify: grub update
  when:
      - ubtu20cis_rule_1_4_2
      - ubtu20cis_set_grub_password
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.4.2
      - grub

- name: "1.4.3 | PATCH | Ensure permissions on bootloader config are configured"
  block:
      - name: "1.4.3 | AUDIT | Ensure permissions on bootloader config are configured | Check for Grub file"
        ansible.builtin.stat:
            path: /boot/grub/grub.cfg
        check_mode: false
        register: ubtu20cis_1_4_3_grub_cfg_status

      - name: "1.4.3 | PATCH | Ensure permissions on bootloader config are configured | Set permissions"
        ansible.builtin.file:
            path: /boot/grub/grub.cfg
            owner: root
            group: root
            mode: 0400
        when:
            - ubtu20cis_1_4_3_grub_cfg_status.stat.exists
  when:
      - ubtu20cis_rule_1_4_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.4.3
      - grub

# The following needs to be set ensure this is in the encrypted form.
- name: "1.4.4 | PATCH | Ensure authentication required for single user mode"
  ansible.builtin.user:
      name: root
      password: "{{ ubtu20cis_root_pw }}"
  when:
      - ubtu20cis_rule_1_4_4
      - ubtu20cis_set_root_password
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.4.4
      - passwd
